# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntagrico', '0006_auto_20171102_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.CharField(max_length=100, verbose_name='Kontierung')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_allocation', to='juntagrico.Member')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.CharField(max_length=100, verbose_name='Kontierung')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_allocation', to='juntagrico.Subscription')),
            ],
        ),
    ]
