# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0006_auto_20171102_1622'),
        ('juntagrico_bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='Konto')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_account', to='juntagrico.Member')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptiontypeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, verbose_name='Konto')),
                ('subscriptiontype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptiontype_account', to='juntagrico.SubscriptionType')),
            ],
        ),
        migrations.RemoveField(
            model_name='memberallocation',
            name='member',
        ),
        migrations.RemoveField(
            model_name='subscriptionallocation',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='MemberAllocation',
        ),
        migrations.DeleteModel(
            name='SubscriptionAllocation',
        ),
    ]
