# Generated by Django 2.0.2 on 2018-05-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_bookkeeping', '0002_auto_20171205_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_account', models.CharField(max_length=100, verbose_name='Debitor-Konto')),
            ],
        ),
    ]
