# Generated by Django 2.2.6 on 2019-11-26 13:35

from django.db import migrations, models
import django.db.models.deletion
import juntagrico.entity


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0018_auto_20191019_2031'),
        ('juntagrico_bookkeeping', '0004_auto_20180529_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='debtor_account',
            field=models.CharField(max_length=10, verbose_name='Debitor-Konto'),
        ),
    ]
