# Generated by Django 2.2.6 on 2019-11-26 13:43

from django.db import migrations, models
import django.db.models.deletion
import juntagrico.entity


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0019_removebills'),
        ('juntagrico_bookkeeping', '0005_auto_20191126_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(verbose_name='Rechnungsdatum')),
                ('ref_number', models.CharField(max_length=30, unique=True, verbose_name='Referenznummer')),
                ('debtor_account', models.CharField(max_length=10, verbose_name='Debitorkonto')),
                ('billable_amount', models.FloatField(verbose_name='Abobetrag')),
                ('offset_kind', models.CharField(choices=[('NONE', 'Keine'), ('CREDIT', 'Gutschrift'), ('DEBIT', 'Lastschrift')], default='NONE', max_length=6, verbose_name='Verrechnung')),
                ('offset_amount', models.FloatField(verbose_name='Verrechnungsbetrag')),
                ('offset_text', models.CharField(max_length=50, verbose_name='Verrechnungstext')),
                ('offset_account', models.CharField(max_length=10, verbose_name='Verrechnungskonto')),
                ('paid', models.BooleanField(default=False, verbose_name='bezahlt')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Zahlungsdatum')),
                ('payment_amount', models.FloatField(verbose_name='Zahlungsbetrag')),
                ('billable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='juntagrico.Billable')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='juntagrico.Member')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
            },
            bases=(models.Model, juntagrico.entity.OldHolder),
        ),
    ]
