# Generated by Django 2.2.6 on 2019-11-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_bookkeeping', '0006_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='debtor_account',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Debitorkonto'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='offset_account',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Verrechnungskonto'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='offset_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Verrechnungstext'),
        ),
    ]
